const os = require('os')
const path = require('path')

function tryRequire(...paths) {
  for (const p of paths) {
    try { return require(p) } catch {}
  }
  return null
}

const platform = os.platform()
const arch = os.arch()
const pkg = 'catcher-napi-http'
const dirname = __dirname

// Load raw napi bindings.
// 1. index.js — generated by `napi build` (exports JsHttpClient directly)
// 2. Direct .node / .so — cargo build fallback for development
let RawClient

const napiJs = tryRequire(path.join(dirname, 'index.js'))
if (napiJs) {
  RawClient = napiJs.JsHttpClient
} else {
  const addon =
    tryRequire(path.join(dirname, 'npm', `${platform}-${arch}`, `${pkg}.node`)) ??
    tryRequire(path.join(dirname, `${pkg}.node`)) ??
    tryRequire(path.join(dirname, `${pkg}.${platform}-${arch}.node`)) ??
    // cargo build fallback (platform-specific shared library)
    tryRequire(path.join(dirname, 'target', 'release', `lib${pkg.replace(/-/g, '_')}.so`)) ??
    tryRequire(path.join(dirname, 'target', 'release', `lib${pkg.replace(/-/g, '_')}.dylib`)) ??
    tryRequire(path.join(dirname, 'target', 'release', `${pkg.replace(/-/g, '_')}.dll`))

  if (!addon) {
    throw new Error(
      `@eric8810/catcher-napi-http: native addon not found.\n` +
      `Run \`npm run build\` in packages/${pkg} (requires Rust).`
    )
  }

  RawClient = addon.JsHttpClient
}

// ── Public wrapper class ────────────────────────────────────

class HttpClient {
  constructor(config) {
    const configJson = typeof config === 'string' ? config : JSON.stringify(config)
    this._raw = new RawClient(configJson)
  }

  async get(url, options) {
    return this._raw.get(url, options ?? undefined)
  }

  async post(url, body, options) {
    return this._raw.post(url, body ?? undefined, options ?? undefined)
  }

  async put(url, body, options) {
    if (this._raw.put) return this._raw.put(url, body ?? undefined, options ?? undefined)
    throw new Error('put() requires rebuilt native addon (cargo build)')
  }

  async delete(url, options) {
    if (this._raw.delete) return this._raw.delete(url, options ?? undefined)
    throw new Error('delete() requires rebuilt native addon (cargo build)')
  }

  async patch(url, body, options) {
    if (this._raw.patch) return this._raw.patch(url, body ?? undefined, options ?? undefined)
    throw new Error('patch() requires rebuilt native addon (cargo build)')
  }

  circuitBreakerState() {
    if (this._raw.circuitBreakerState) return this._raw.circuitBreakerState()
    return 'closed'
  }

  metrics() {
    if (this._raw.metrics) return this._raw.metrics()
    return null
  }

  setAdaptiveTimeout(minTimeoutMs, maxTimeoutMs, multiplier, windowSize) {
    if (this._raw.setAdaptiveTimeout) return this._raw.setAdaptiveTimeout(minTimeoutMs, maxTimeoutMs, multiplier, windowSize)
  }

  disableAdaptiveTimeout() {
    if (this._raw.disableAdaptiveTimeout) return this._raw.disableAdaptiveTimeout()
  }

  cancelAll() {
    if (this._raw.cancelAll) return this._raw.cancelAll()
  }

  cancelRequest(requestId) {
    if (this._raw.cancelRequest) return this._raw.cancelRequest(requestId)
    return false
  }

  nextRequestId() {
    if (this._raw.nextRequestId) return this._raw.nextRequestId()
    return 0
  }

  executeStream(method, url, body, options, onChunk) {
    if (this._raw.executeStream) return this._raw.executeStream(method, url, body ?? undefined, options ?? undefined, onChunk)
    throw new Error('executeStream() requires rebuilt native addon (cargo build)')
  }
}

module.exports = { HttpClient }
