export { createWebClient } from './http/client.js'
export { createWebSocketClient } from './ws/client.js'
export { createSSEStream, createSSEClient } from './sse/index.js'
export type { IHttpClient, RequestConfig, HttpClientConfig, HttpResponse } from '@eric8810/catcher-core'
export type { WebSocketClientOptions, WebSocketClient, WsStatus } from './ws/client.js'
export type { SSEStreamOptions, SSEClientOptions, SSEStream, SSEClient, SSETimeoutError } from '@eric8810/catcher-core'
