[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-ld_classic"]

[target.x86_64-apple-ios]
rustflags = []

[target.aarch64-apple-ios-sim]
rustflags = []

[target.x86_64-apple-ios-sim]
rustflags = []
