const os = require('os')
const path = require('path')

function tryRequire(...paths) {
  for (const p of paths) {
    try { return require(p) } catch {}
  }
  return null
}

const platform = os.platform()
const arch = os.arch()
const pkg = 'catcher-napi-ws'
const dirname = __dirname

// Load raw napi bindings.
// 1. index.js — generated by `napi build` (exports JsWsClient directly)
// 2. Direct .node / .so — cargo build fallback for development
let RawClient

const napiJs = tryRequire(path.join(dirname, 'index.js'))
if (napiJs) {
  RawClient = napiJs.JsWsClient
} else {
  const addon =
    tryRequire(path.join(dirname, 'npm', `${platform}-${arch}`, `${pkg}.node`)) ??
    tryRequire(path.join(dirname, `${pkg}.node`)) ??
    tryRequire(path.join(dirname, `${pkg}.${platform}-${arch}.node`)) ??
    // cargo build fallback (platform-specific shared library)
    tryRequire(path.join(dirname, 'target', 'release', `lib${pkg.replace(/-/g, '_')}.so`)) ??
    tryRequire(path.join(dirname, 'target', 'release', `lib${pkg.replace(/-/g, '_')}.dylib`)) ??
    tryRequire(path.join(dirname, 'target', 'release', `${pkg.replace(/-/g, '_')}.dll`))

  if (!addon) {
    throw new Error(
      `@eric8810/catcher-napi-ws: native addon not found.\n` +
      `Run \`npm run build\` in packages/${pkg} (requires Rust).`
    )
  }

  RawClient = addon.JsWsClient
}

// ── Public wrapper class ────────────────────────────────────

class WsClient {
  constructor(config, onEvent) {
    const configJson = typeof config === 'string' ? config : JSON.stringify(config)
    this._raw = new RawClient(configJson, onEvent)
  }

  send(data) {
    return this._raw.send(data)
  }

  /** Send a binary message (Buffer, ArrayBuffer, or Uint8Array) */
  sendBinary(data) {
    // napi expects Buffer — coerce ArrayBuffer/Uint8Array
    if (data instanceof ArrayBuffer) {
      data = Buffer.from(data)
    } else if (data instanceof Uint8Array) {
      data = Buffer.from(data.buffer, data.byteOffset, data.byteLength)
    }
    return this._raw.send_binary(data)
  }

  close(code, reason) {
    return this._raw.close(code ?? null, reason ?? null)
  }
}

module.exports = { WsClient }
